services:
  nocouncil:
    image: ghcr.io/tapilab/nocouncil:latest
    env_file: .env
    ports:
      - "5003:5003"
    volumes:
      # ensures local code is used over image
      - ./:/app
      # optional: persist seeded data so restarts don't re-download
      - nocouncil_models:/models
      - nocouncil_data:/data
    command: gunicorn app:app --reload --bind 0.0.0.0:5003

volumes:
  nocouncil_models:
  nocouncil_data:
